'use strict';

var ngConstant = require('gulp-ng-constant');
var gulp = require('gulp');

var $ = require('gulp-load-plugins')();

gulp.task('config', function () {
  gulp.src('app/config.json')
    .pipe(ngConstant({
      name: 'my.module.config',
      deps: ['ngAnimate'],
      constants: { myPropCnt: 'hola!' },
      wrap: '"use strict";\n// DO NOT EDIT THIS FILE, EDIT THE GULP TASK SETTINGS INSTEAD WHICH GENERATES THIS FILE\n<%= __ngModule %>',
    }))
    // Writes config.js to dist/ folder
    .pipe(gulp.dest('dist'));
});